/*
    Schema file for hsqldb
*/

CREATE TABLE department (
department_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
department_name VARCHAR(50)
);

CREATE TABLE section (
section_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
section_name VARCHAR(50),
department_id INT,
CONSTRAINT section_department_fk FOREIGN KEY (department_id) REFERENCES department (department_id)
);

CREATE TABLE office (
office_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
office_name VARCHAR(50)
);

CREATE TABLE person (
person_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
person_name VARCHAR(50)
);

CREATE TABLE student (
person_id INT UNIQUE,
student_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
CONSTRAINT student_person_fk FOREIGN KEY (person_id) REFERENCES person (person_id)
);

CREATE TABLE staff (
person_id INT UNIQUE,
staff_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
office_id INT,
CONSTRAINT staff_person_fk FOREIGN KEY (person_id) REFERENCES person (person_id),
CONSTRAINT staff_office_fk FOREIGN KEY (office_id) REFERENCES office (office_id)
);

CREATE TABLE registry (
registry_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
section_id INT,
student_id INT,
CONSTRAINT registry_section_fk FOREIGN KEY (section_id) REFERENCES section (section_id),
CONSTRAINT registry_student_fk FOREIGN KEY (student_id) REFERENCES student (student_id)
);

CREATE TABLE attendance (
attendance_id TINYINT PRIMARY KEY,
attendance_type VARCHAR(10)
);

CREATE TABLE student_attendance (
student_attendance_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
student_id INT,
date DATE DEFAULT CURRENT_DATE,
attendance_id TINYINT,
section_id INT,
CONSTRAINT student_attendance_student_fk FOREIGN KEY (student_id) REFERENCES student (student_id),
CONSTRAINT student_attendance_attendance_fk FOREIGN KEY (attendance_id) REFERENCES attendance (attendance_id),
CONSTRAINT student_attendance_section_fk FOREIGN KEY (section_id) REFERENCES section (section_id)
);

CREATE TABLE staff_attendance (
staff_attendance_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
staff_id INT,
date DATE DEFAULT CURRENT_DATE,
attendance_id TINYINT,
CONSTRAINT staff_attendance_staff_fk FOREIGN KEY (staff_id) REFERENCES staff (staff_id),
CONSTRAINT staff_attendance_attendance_fk FOREIGN KEY (attendance_id) REFERENCES attendance (attendance_id)
);
